project_id = "weluosjthorckfmhjaol"

[functions.gmail-auth]
verify_jwt = false

[functions.gmail-callback]
verify_jwt = false

[functions.gmail-scan]
verify_jwt = false

[functions.track-shipment]
verify_jwt = false
